name: 'deployment of azure policies'
on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
        - "Policy-Assignment/**/*"

jobs:
  build-and-deploy:
      env:
       TF_IN_AUTOMATION: true
       TF_INPUT: false
       TF_WORKING_DIR: Policy/Policy-Assignment/Initiatives
       ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
       ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
       ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
       ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      runs-on: ubuntu-latest
      steps:
     # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3
        - name: Terraform Init
          run: terraform init
        - name: Terraform Format
          run: terraform fmt -check
        - name: Terraform Validate
          run: terraform validate -no-color
