name: 'deployment of azure policies'
on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
        - "Policy-Assignment/**/*"

jobs:
  build-and-deploy:
      env:
       TF_IN_AUTOMATION: true
       TF_INPUT: false
       ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
       ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
       ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
       ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      runs-on: ubuntu-latest
      steps:
     # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3
        - name: Find configuration files
          run: |
            find Policy -name "*.tf"
            find Policy -name "*.json"
          id: find_files
        - name: Deploy policies
          run: |
            terraform init
            terraform validate
            terraform plan -var-file=variables.tfvars -out=tfplan -input=false -no-color
            terraform apply -input=false -auto-approve tfplan
          if: steps.find_files.outputs.stdout != ''
